# Generated by Django 4.1.1 on 2022-10-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='td',
            old_name='user_id',
            new_name='user',
        ),
    ]
